server:
  port: 8888

management:
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: git
  application:
    name: server-config
  cloud:
    config:
      override-system-properties: true
      server:
        git:
          uri: https://github.com/gerometan/testproject.git
          skipSslValidation: true
          clone-on-start: false
          search-paths:
            server-config/src/main/resources/,
            server-config/src/main/resources/config
          force-pull: true
          timeout: 2
          allowOverride: true
          username: gerometan
          password: mermaid$0206
logging:
  level.: TRACE