server:
  port: 8762

management:
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: native
  cloud:
    client.hostname: ${spring.cloud.client.ip-address:localhost}
    config:
      override-system-properties: false
      server:
        native:
          search-locations:
            classpath:/config/,
            classpath:/config/client-config-first,
            classpath:/config/client-discovery-first
  application:
    name: server-config
