server:
  port: 8888

management:
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: git
  application:
    name: testModules
  cloud:
    config:
      override-system-properties: true
      server:
        git:
          uri: https://github.com/gerometan/testModules
          skipSslValidation: true
          clone-on-start: true
          search-paths: /config/pro*, config/prod*
          force-pull: true
          basedir: ${user.home}/gerome
          timeout: 2
          allowOverride: true
          username: gerometan
          password: mermaid$0206
logging:
  level.: TRACE